services:
  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "trainbooking_db"
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
# volumes:
#   db_data:
